[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"

[[redirects]]
  from   = "https://getchip.cc/*"
  to     = "https://docs.getchip.cc/:splat"
  status = 301
  force  = true

[[redirects]]
  from   = "https://www.getchip.cc/*"
  to     = "https://docs.getchip.cc/:splat"
  status = 301
  force  = true

[[redirects]]
  from   = "https://docs-getchip-cc.netlify.com/*"
  to     = "https://docs.getchip.cc/:splat"
  status = 301
  force  = true

[[redirects]]
  from   = "/chip_pro_devkit.html"
  to     = "/chip-pro-devkit"
  status = 301
  force  = true

[[redirects]]
  from   = "/chip_pro.html"
  to     = "/chip-pro"
  status = 301
  force  = true

[[redirects]]
  from   = "/chip.html"
  to     = "/chip"
  status = 301
  force  = true

[[redirects]]
  from   = "/dip.html"
  to     = "/dip"
  status = 301
  force  = true

[[redirects]]
  from   = "/gadget.html"
  to     = "/gadget"
  status = 301
  force  = true

[[redirects]]
  from   = "/pocketchip.html"
  to     = "/pocketchip"
  status = 301
  force  = true
