[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
    Content-Type = "image/x-icon"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[headers]]
  for = "/javascripts/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[headers]]
  for = "/stylesheets/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[redirects]]
  from   = "https://getchip.cc/*"
  to     = "https://docs.getchip.cc/:splat"
  status = 301
  force  = true

[[redirects]]
  from   = "https://www.getchip.cc/*"
  to     = "https://docs.getchip.cc/:splat"
  status = 301
  force  = true

[[redirects]]
  from   = "https://docs-getchip-cc.netlify.app/*"
  to     = "https://docs.getchip.cc/:splat"
  status = 301
  force  = true

[[redirects]]
  from   = "/pro.html"
  to     = "/chip_pro_devkit.html"
  status = 301
  force  = true
